apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tag-management
  namespace: prakarsa
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: tag-management.prakarsa.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tag-management
                port:
                  number: 80